main:
  config: configs/main.yaml
  config_button: ''
  in_path: C:/Users/smkim/Downloads/__input/orinnxraw_4056x3040
  in_path_button: C:/Users/smkim/Downloads/__input/orinnxraw_4056x3040
  out_path: C:/Users/smkim/Downloads/__output/orinnxraw_4056x3040
  out_path_button: C:/Users/smkim/Downloads/__output/orinnxraw_4056x3040
  cpu: true
  cuda: false
  width: 4056
  height: 3040
  bit_depth: 12
  gbrg: false
  bggr: true
  rggb: false
  grbg: false
  srgb: false
easy:
  blc: true
  blc_bl: 256
  cfa: true
  awb: true
  awb_gw: true
  awb_gain:
    r: 2
    g: 1
    b: 2
  ccm: true
  ccm_matrix:
    r2r: 1.8
    r2g: -0.8
    r2b: 0
    g2r: -0.3
    g2g: 1.5
    g2b: -0.2
    b2r: 0
    b2g: -0.8
    b2b: 1.8
  gac: true
  gac_gain: 0.1
  gac_gamma: 2.2
fast:
  dpc: false
  dpc_diff: 30
  blc: false
  blc_bl: 256
  lsc: true
  lsc_intensity: 10
  aaf: false
  awb: false
  awb_gw: true
  awb_gain:
    r: 1860
    gr: 1024
    gb: 1024
    b: 1280
  cnf: false
  cnf_diff: 0
  cfa: false
  cfa_malvar: true
  cfa_bilinear: false
  ccm: false
  ccm_matrix:
    r2r: 1800
    r2g: -800
    r2b: 0
    r2o: 0
    g2r: -300
    g2g: 1500
    g2b: -200
    g2o: 0
    b2r: 0
    b2g: -800
    b2b: 1800
    b2o: 0
  gac: false
  gac_gain: 256
  gac_gamma: 0.42
  csc: true
  nlm: false
  nlm_patch_size: 3
  nlm_search_window_size: 9
  nlm_h: 10
  bnf: false
  bnf_intensity_sigma: 0.8
  bnf_spatial_sigma: 0.8
  ceh: false
  ceh_tile_width: 4
  ceh_tile_height: 6
  ceh_clip_limit: 0.01
  eeh: false
  eeh_gain: 384
  eeh_flat_threshold: 4
  eeh_edge_threshold: 8
  eeh_delta_threshold: 64
  fcs: false
  fcs_delta_min: 8
  fcs_delta_max: 32
  hsc: true
  hsc_gain: 256
  hsc_offset: 0
  bcc: true
  bcc_gain: 256
  bcc_offset: 0
nr3d:
  fps: 30
  nr3d: false
  filter: false
  filter_nr3d: false
  nr3d_filter: true
  num_frames: 7
  threshold: 0.6
  eeh: false
  eeh_ksize: 3
  eeh_edge_factor: 0.3
  eeh_signal_factor: 1
  lpf_luma: true
  lpf_luma_bnf: true
  lpf_luma_median: false
  lpf_luma_ksize: 15
  lpf_luma_bnf_sigma:
    color: 75
    space: 75
  lpf_chroma: true
  lpf_chroma_median: true
  lpf_chroma_ksize: 33
